const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `Enjoy our rich, scrumptuous buttermilk pancakes topped with fresh churned butter, with fresh fruit and maple syrup, with a side of whipped cream `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `Enjoy a flame-broiled burger topped with bacon, lettuce, tomato, and pickles with a side of fries `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `This shake blends fresh cream, premium ice cream, and vanilla to make the perfect taste; topped with whippled cream, a cherry, and sprinkles`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Enjoy your fried eggs over toast along with a side of shredded, baked potatoes `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `This burger is sure to please your tastebuds as it is topped with an egg scramble, lettuce, tomato, pickle, and our house sauce `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `This shake is sure to please anyone with its rich blend of oreo cookies, fresh cream, and premium ice cream, topped with a fresh strawberry`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `This breakfast sandwich combines fried eggs cheese, bacon, lettuce, and tomato, topped with mayo for a perfect taste `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `This classic combo is sure to please anyone with a flame-broiled burger topped with cheese, tomato, lettuce, and our house sauce with a side of fries  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `Come with your quarantine buddy to share a simple, but rich vanilla shake`,
    },
  ];
  export default menu;